// This file is autogenerated by scripts/build-registry.mts.
// Do not edit this file directly.
// Component index for previews. File contents live in __items__.json (Workers-safe).

import * as React from "react";

export const Index = {
	"agency-hero-01": {
		name: "agency-hero-01",
		title: "Agency Hero 01",
		description: "Animated agency hero.",
		type: "registry:block",
		files: [{"path":"src/registry/blocks/agency-hero-01/agency-hero-01.tsx","type":"registry:component","target":"@components/agency-hero-01.tsx"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/blocks/agency-hero-01/agency-hero-01")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for agency-hero-01");
			}
			return { default: module.default };
		}),
		categories: ["hero"],
		meta: {"createdAt":"2026-07-17","iframeHeight":760,"previewClassName":"min-h-screen"},
	},
	"3d-button": {
		name: "3d-button",
		title: "3D Button",
		description: "Add physical depth and responsive press feedback to primary actions.",
		type: "registry:component",
		files: [{"path":"src/registry/components/3d-button/3d-button.tsx","type":"registry:component","target":"@components/3d-button.tsx"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/components/3d-button/3d-button")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for 3d-button");
			}
			return { default: module.default };
		}),
		categories: ["buttons"],
		meta: {"createdAt":"2026-07-20","image":"https://cdn.srb.codes/images/components/3d-button-light","video":"https://cdn.srb.codes/videos/components/3d-button-light"},
	},
	"world-map": {
		name: "world-map",
		title: "Interactive World Map",
		description: "Explore countries with zoom, pan, selection, and hover details.",
		type: "registry:component",
		files: [{"path":"src/registry/components/world-map/world-map.tsx","type":"registry:component","target":"@components/world-map.tsx"},{"path":"public/data/world-map.geo.json","type":"registry:file","target":"~/public/data/world-map.geo.json"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/components/world-map/world-map")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for world-map");
			}
			return { default: module.default };
		}),
		categories: [],
		meta: {"createdAt":"2026-05-05","video":"https://cdn.srb.codes/videos/components/world-map","image":"https://cdn.srb.codes/images/components/world-map"},
	},
	"contextful-save-button": {
		name: "contextful-save-button",
		title: "Contextful Save Button",
		description: "Show async save progress and outcomes without leaving the button.",
		type: "registry:component",
		files: [{"path":"src/registry/components/contextful-save-button/contextful-save-button.tsx","type":"registry:component","target":"@components/contextful-save-button.tsx"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/components/contextful-save-button/contextful-save-button")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for contextful-save-button");
			}
			return { default: module.default };
		}),
		categories: [],
		meta: {"createdAt":"2026-07-19","video":"https://cdn.srb.codes/videos/components/animated-save-button","image":"https://cdn.srb.codes/images/components/animated-save-button"},
	},
	"animated-arrow": {
		name: "animated-arrow",
		title: "Animated Arrow",
		description: "Slide an arrow across its container when its parent is hovered.",
		type: "registry:component",
		files: [{"path":"src/registry/components/animated-arrow/animated-arrow.tsx","type":"registry:component","target":"@components/animated-arrow.tsx"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/components/animated-arrow/animated-arrow")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for animated-arrow");
			}
			return { default: module.default };
		}),
		categories: [],
		meta: {"createdAt":"2026-07-19","video":"https://cdn.srb.codes/videos/components/animated-arrow","image":"https://cdn.srb.codes/images/components/animated-arrow"},
	},
	"scribbled-text": {
		name: "scribbled-text",
		title: "Scribbled Text",
		description: "Mark inline text with colorful hand-drawn annotations.",
		type: "registry:component",
		files: [{"path":"src/registry/components/scribbled-text/scribbled-text.tsx","type":"registry:component","target":"@components/scribbled-text.tsx"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/components/scribbled-text/scribbled-text")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for scribbled-text");
			}
			return { default: module.default };
		}),
		categories: ["typography"],
		meta: {"createdAt":"2026-07-20","image":"https://cdn.srb.codes/images/components/scribbled-text","video":"https://cdn.srb.codes/videos/components/scribbled-text"},
	},
	"3d-button-demo": {
		name: "3d-button-demo",
		title: undefined,
		description: "",
		type: "registry:example",
		files: [{"path":"src/registry/examples/3d-button-demo.tsx","type":"registry:example"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/examples/3d-button-demo")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for 3d-button-demo");
			}
			return { default: module.default };
		}),
		categories: undefined,
		meta: {"previewClassName":"min-h-[40rem] w-full p-0"},
	},
	"world-map-demo": {
		name: "world-map-demo",
		title: undefined,
		description: "",
		type: "registry:example",
		files: [{"path":"src/registry/examples/world-map-demo.tsx","type":"registry:example"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/examples/world-map-demo")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for world-map-demo");
			}
			return { default: module.default };
		}),
		categories: undefined,
		meta: {"previewClassName":"min-h-72 w-full"},
	},
	"contextful-save-button-demo": {
		name: "contextful-save-button-demo",
		title: undefined,
		description: "",
		type: "registry:example",
		files: [{"path":"src/registry/examples/contextful-save-button-demo.tsx","type":"registry:example"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/examples/contextful-save-button-demo")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for contextful-save-button-demo");
			}
			return { default: module.default };
		}),
		categories: undefined,
		meta: {"previewClassName":"min-h-72 place-items-center content-center"},
	},
	"animated-arrow-demo": {
		name: "animated-arrow-demo",
		title: undefined,
		description: "",
		type: "registry:example",
		files: [{"path":"src/registry/examples/animated-arrow-demo.tsx","type":"registry:example"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/examples/animated-arrow-demo")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for animated-arrow-demo");
			}
			return { default: module.default };
		}),
		categories: undefined,
		meta: {"previewClassName":"min-h-72 place-items-center content-center"},
	},
	"scribbled-text-demo": {
		name: "scribbled-text-demo",
		title: undefined,
		description: "",
		type: "registry:example",
		files: [{"path":"src/registry/examples/scribbled-text-demo.tsx","type":"registry:example"}],
		component: React.lazy(async () => {
			const module = (await import("@/registry/examples/scribbled-text-demo")) as unknown as {
				default?: React.ComponentType;
			};
			if (!module.default) {
				throw new Error("No default export found for scribbled-text-demo");
			}
			return { default: module.default };
		}),
		categories: undefined,
		meta: {"previewClassName":"min-h-[56rem] w-full p-0"},
	}
} as const;

export type RegistryIndexName = keyof typeof Index;
