// This file is autogenerated by scripts/build-registry.mts.
// Do not edit this file directly.

import * as React from "react";

export const Index = {
	"agency-hero-01": {
		name: "agency-hero-01",
		title: "Agency Hero 01",
		description:
			"Animated agency hero with availability badge, CTAs, background art, and tech carousel.",
		type: "registry:block",
		files: [
			{
				path: "src/registry/blocks/agency-hero-01/agency-hero-01.tsx",
				type: "registry:component",
				target: "@components/agency-hero-01.tsx",
			},
		],
		component: React.lazy(async () => {
			const module = await import(
				"@/registry/blocks/agency-hero-01/agency-hero-01"
			);
			if (!module.default) {
				throw new Error("No default export found for agency-hero-01");
			}
			return { default: module.default };
		}),
		categories: ["marketing"],
		meta: {
			createdAt: "2026-07-17",
			iframeHeight: 760,
			previewClassName: "min-h-screen",
		},
	},
	"gradient-hero-01": {
		name: "gradient-hero-01",
		title: "Gradient Hero 01",
		description:
			"A simple centered hero with a warm cinematic gradient, compact badge, short copy, and two actions.",
		type: "registry:block",
		files: [
			{
				path: "src/registry/blocks/gradient-hero-01/gradient-hero-01.tsx",
				type: "registry:component",
				target: "@components/gradient-hero-01.tsx",
			},
		],
		component: React.lazy(async () => {
			const module = await import(
				"@/registry/blocks/gradient-hero-01/gradient-hero-01"
			);
			if (!module.default) {
				throw new Error("No default export found for gradient-hero-01");
			}
			return { default: module.default };
		}),
		categories: ["marketing"],
		meta: {
			createdAt: "2026-06-30",
			iframeHeight: 760,
			previewClassName: "min-h-screen",
		},
	},
} as const;

export type RegistryIndexName = keyof typeof Index;
