// Thanks @shadcn for the inspiration and code references in this file.

import { promises as fs } from "node:fs";
import path from "node:path";
import {
	type Registry,
	type RegistryItem,
	registrySchema,
} from "shadcn/schema";

import { registry } from "@/registry/index";

/**
 * First stage of TentUI's registry pipeline.
 *
 * Authored source:
 * - src/registry/index.ts
 * - src/registry/blocks/**
 *
 * Persistent outputs:
 * - registry.json (source registry consumed by `shadcn build`)
 * - src/registry/__index__.tsx (lazy component index used by previews)
 * - src/registry/__blocks__.json (small block listing payload)
 *
 * The package's `registry:build` task runs `shadcn build` after this script to
 * produce public/r/registry.json and public/r/{name}.json.
 */

const appRoot = process.cwd();
const registryPath = path.join(appRoot, "src/registry");

function withLocalFilePaths(item: RegistryItem): RegistryItem {
	return {
		...item,
		files:
			item.files?.map((file) => ({
				...file,
				path: file.path.startsWith("src/")
					? file.path
					: `src/registry/${file.path}`,
			})) ?? [],
	};
}

function getComponentImportPath(item: RegistryItem) {
	const componentFile = item.files?.find((file) =>
		["registry:block", "registry:component", "registry:example"].includes(
			file.type,
		),
	);

	if (!componentFile) {
		return null;
	}

	const filePath = componentFile.path.startsWith("src/")
		? componentFile.path.replace(/^src\//, "@/")
		: `@/registry/${componentFile.path}`;

	return filePath.replace(/\.(?:ts|tsx)$/, "");
}

function serialize(value: unknown) {
	return JSON.stringify(value);
}

function buildIndexSource(items: RegistryItem[]) {
	const entries = items
		.filter((item) => item.files?.length)
		.map((item) => {
			const localItem = withLocalFilePaths(item);
			const componentImportPath = getComponentImportPath(item);
			// Blocks are authored as `export default`. Do not probe named exports —
			// that hides missing defaults and makes the generated index harder to trust.
			const component = componentImportPath
				? `React.lazy(async () => {
			const module = await import(${serialize(componentImportPath)});
			if (!module.default) {
				throw new Error(${serialize(`No default export found for ${item.name}`)});
			}
			return { default: module.default };
		})`
				: "null";

			return `${serialize(item.name)}: {
		name: ${serialize(localItem.name)},
		title: ${serialize(localItem.title)},
		description: ${serialize(localItem.description ?? "")},
		type: ${serialize(localItem.type)},
		files: ${serialize(localItem.files ?? [])},
		component: ${component},
		categories: ${serialize(localItem.categories)},
		meta: ${serialize(localItem.meta)},
	}`;
		});

	return `// This file is autogenerated by scripts/build-registry.mts.
// Do not edit this file directly.

import * as React from "react";

export const Index = {
	${entries.join(",\n\t")}
} as const;

export type RegistryIndexName = keyof typeof Index;
`;
}

function createdAtTimestamp(item: RegistryItem) {
	const createdAt = item.meta?.createdAt;
	return typeof createdAt === "string" ? new Date(createdAt).getTime() : 0;
}

function buildBlocksPayload(items: RegistryItem[]) {
	return items
		.filter((item) => item.type === "registry:block")
		.toSorted((a, b) => createdAtTimestamp(b) - createdAtTimestamp(a))
		.map((item) => ({
			name: item.name,
			description: item.description,
			categories: item.categories,
		}));
}

async function readFileIfExists(filePath: string) {
	try {
		return await fs.readFile(filePath, "utf8");
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === "ENOENT") {
			return null;
		}
		throw error;
	}
}

async function writeIfChanged(filePath: string, content: string) {
	if ((await readFileIfExists(filePath)) === content) {
		return false;
	}

	await fs.mkdir(path.dirname(filePath), { recursive: true });
	await fs.writeFile(filePath, content, "utf8");
	return true;
}

export async function buildRegistry(sourceRegistry: Registry) {
	const parsed = registrySchema.safeParse(sourceRegistry);
	if (!parsed.success) {
		throw new Error(`Invalid registry:\n${parsed.error.message}`);
	}

	const publicRegistry = {
		$schema: "https://ui.shadcn.com/schema/registry.json",
		name: "tentui",
		homepage: "https://tentui.com/blocks",
		items: parsed.data.items
			.filter((item) => item.type !== "registry:example")
			.map(withLocalFilePaths),
	};

	const outputs = [
		{
			path: path.join(appRoot, "registry.json"),
			content: `${JSON.stringify(publicRegistry, null, 2)}\n`,
		},
		{
			path: path.join(registryPath, "__index__.tsx"),
			content: buildIndexSource(parsed.data.items),
		},
		{
			path: path.join(registryPath, "__blocks__.json"),
			content: `${JSON.stringify(buildBlocksPayload(parsed.data.items), null, 2)}\n`,
		},
	];

	const changed = await Promise.all(
		outputs.map(async (output) => ({
			path: path.relative(appRoot, output.path),
			changed: await writeIfChanged(output.path, output.content),
		})),
	);

	for (const output of changed) {
		console.log(`${output.changed ? "wrote" : "unchanged"} ${output.path}`);
	}
}

await buildRegistry(registry);
